import TodoProvider from "@/provider/TodoProvider";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";
import "./global.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "ToDo App",
  description: "Generated by create next app",
};
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <TodoProvider>{children}</TodoProvider>
      </body>
    </html>
  );
};

export default RootLayout;
